DROP TABLE IF EXISTS audit_log CASCADE;
DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE users (
    id         BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cognito_id VARCHAR(80)  NOT NULL UNIQUE,
    username   VARCHAR(60)  NOT NULL,
    name       VARCHAR(80)  NOT NULL,
    email      VARCHAR(120),
    phone      VARCHAR(30),
    created_at TIMESTAMP    NOT NULL DEFAULT NOW()
);

CREATE TABLE audit_log (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_name VARCHAR(40)  NOT NULL,
    entity_id   BIGINT       NOT NULL,
    action      VARCHAR(10)  NOT NULL,
    user_sub    VARCHAR(80)  NOT NULL,
    user_name   VARCHAR(60)  NOT NULL,
    old_values  VARCHAR(2000),
    new_values  VARCHAR(2000),
    created_at  TIMESTAMP    NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_audit_action CHECK (action IN ('INSERT', 'UPDATE', 'DELETE'))
);

CREATE INDEX idx_users_username ON users (username);
CREATE INDEX idx_audit_entity   ON audit_log (entity_name, entity_id);
