-- =====================================================================================
--  MatchPoint · Esquema del microservicio `users` — PostgreSQL 16
--
--  DOCUMENTACION del modelo. En ejecucion el esquema lo crea Hibernate
--  (ddl-auto=update) sobre la base `users_db`, que es EXCLUSIVA de este microservicio.
--
--  La unica funcion del micro: asociar el `sub` de Cognito con los datos propios del
--  usuario. matchpoint jamas lee esta base: pide el perfil por HTTP.
-- =====================================================================================

DROP TABLE IF EXISTS audit_log CASCADE;
DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE users (
    id         BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cognito_id VARCHAR(80)  NOT NULL UNIQUE,   -- claim sub del token; 1 usuario de Cognito = 1 perfil
    username   VARCHAR(60)  NOT NULL,          -- claim username; es la llave que usa matchpoint
    name       VARCHAR(80)  NOT NULL,
    email      VARCHAR(120),
    phone      VARCHAR(30),
    created_at TIMESTAMP    NOT NULL DEFAULT NOW()
);

-- =====================================================================================
--  TABLA: audit_log  (Criterio 2: quien, que, cuando, valores anteriores/nuevos)
-- =====================================================================================
CREATE TABLE audit_log (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_name VARCHAR(40)  NOT NULL,
    entity_id   BIGINT       NOT NULL,
    action      VARCHAR(10)  NOT NULL,
    user_sub    VARCHAR(80)  NOT NULL,         -- sub del token de Cognito
    user_name   VARCHAR(60)  NOT NULL,         -- claim username del token
    old_values  VARCHAR(2000),                 -- enmascarado: nunca correos ni telefonos completos
    new_values  VARCHAR(2000),
    created_at  TIMESTAMP    NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_audit_action CHECK (action IN ('INSERT', 'UPDATE', 'DELETE'))
);

CREATE INDEX idx_users_username ON users (username);
CREATE INDEX idx_audit_entity   ON audit_log (entity_name, entity_id);
