-- =====================================================================================
--  MatchPoint · Esquema del microservicio `matchpoint` — PostgreSQL 16
--
--  DOCUMENTACION del modelo. En ejecucion el esquema lo crea Hibernate
--  (ddl-auto=update) sobre la base `matchpoint_db`; este archivo sirve para leer el
--  modelo de un vistazo y para recrearlo a mano si hiciera falta (con ddl-auto=validate).
--
--  5 tablas de dominio + 1 de auditoria. 'courts' fusiona el complejo deportivo y la
--  cancha del diseño original: cada cancha lleva su sector, si tiene parqueo y su dueño.
--
--  Relaciones:
--    courts       1:N reservations   (una cancha tiene muchas reservas)
--    courts       1:N tournaments    (una cancha puede ser sede de varios torneos; opcional)
--    tournaments  1:N teams          (un torneo tiene muchos equipos)
--    tournaments  1:N matches        (un torneo tiene muchos partidos)
--    teams (N:M) teams via matches   ('matches' es la entidad asociativa: 2 equipos por partido)
--    tournaments  N:1 teams          (champion_team_id -> equipo campeon, opcional)
--
--  NADA aqui referencia la base del microservicio `users`: el dato ajeno (owner_name)
--  llega por HTTP y se guarda como copia.
-- =====================================================================================

DROP TABLE IF EXISTS audit_log CASCADE;
DROP TABLE IF EXISTS matches CASCADE;
DROP TABLE IF EXISTS teams CASCADE;
DROP TABLE IF EXISTS tournaments CASCADE;
DROP TABLE IF EXISTS reservations CASCADE;
DROP TABLE IF EXISTS courts CASCADE;

-- =====================================================================================
--  TABLA: courts  (complejo + cancha fusionados)
-- =====================================================================================
CREATE TABLE courts (
    id             BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           VARCHAR(80)  NOT NULL,
    sector         VARCHAR(40)  NOT NULL,
    has_parking    BOOLEAN      NOT NULL DEFAULT FALSE,
    sport_type     VARCHAR(30)  NOT NULL,
    floor_type     VARCHAR(40)  NOT NULL,
    price_per_hour DECIMAL(8,2) NOT NULL,
    active         BOOLEAN      NOT NULL DEFAULT TRUE,
    manager_user   VARCHAR(60)  NOT NULL,          -- claim username del JWT (dueño MANAGER)
    created_at     TIMESTAMP    NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_courts_sport_type CHECK (sport_type = 'BASKET'),
    CONSTRAINT chk_courts_price      CHECK (price_per_hour > 0)
);

-- =====================================================================================
--  TABLA: reservations
-- =====================================================================================
CREATE TABLE reservations (
    id               BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    court_id         BIGINT      NOT NULL,
    owner_user       VARCHAR(60) NOT NULL,          -- claim username del JWT (PLAYER dueño)
    owner_name       VARCHAR(80) NOT NULL,          -- COPIA de lo que devolvio el micro `users`
    starts_at        TIMESTAMP   NOT NULL,
    duration_minutes INTEGER     NOT NULL,
    status           VARCHAR(20) NOT NULL DEFAULT 'CONFIRMED',
    created_at       TIMESTAMP   NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_reservations_court
        FOREIGN KEY (court_id) REFERENCES courts (id) ON DELETE CASCADE,
    CONSTRAINT chk_reservations_status   CHECK (status IN ('CONFIRMED', 'CANCELLED')),
    CONSTRAINT chk_reservations_duration CHECK (duration_minutes > 0)
);

-- =====================================================================================
--  TABLA: tournaments
-- =====================================================================================
CREATE TABLE tournaments (
    id               BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name             VARCHAR(80)  NOT NULL,
    sport_type       VARCHAR(30)  NOT NULL,
    max_teams        INTEGER      NOT NULL,
    prize            VARCHAR(150),                   -- OPCIONAL
    status           VARCHAR(20)  NOT NULL DEFAULT 'REGISTRATION',
    manager_user     VARCHAR(60)  NOT NULL,          -- claim username del JWT (dueño MANAGER)
    court_id         BIGINT,                         -- sede opcional (FK a courts)
    champion_team_id BIGINT,                         -- FK a teams (se agrega abajo), nullable
    created_at       TIMESTAMP    NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_tournaments_court
        FOREIGN KEY (court_id) REFERENCES courts (id) ON DELETE SET NULL,
    CONSTRAINT chk_tournaments_sport_type CHECK (sport_type = 'BASKET'),
    CONSTRAINT chk_tournaments_status
        CHECK (status IN ('REGISTRATION', 'IN_PROGRESS', 'FINISHED')),
    CONSTRAINT chk_tournaments_max_teams
        CHECK (max_teams IN (2, 4, 8, 16, 32))       -- potencia de 2: cuadro perfecto sin byes
);

-- =====================================================================================
--  TABLA: teams  (datos externos + datos internos embebidos)
-- =====================================================================================
CREATE TABLE teams (
    id                 BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tournament_id      BIGINT      NOT NULL,
    registered_by_user VARCHAR(60) NOT NULL,          -- claim username del JWT (PLAYER que inscribe)

    -- datos externos
    name               VARCHAR(80)  NOT NULL,
    contact_name       VARCHAR(80)  NOT NULL,
    contact_email      VARCHAR(120) NOT NULL,
    contact_phone      VARCHAR(30)  NOT NULL,

    -- datos internos (estado dentro del torneo)
    eliminated         BOOLEAN NOT NULL DEFAULT FALSE,
    matches_played     INTEGER NOT NULL DEFAULT 0,
    matches_won        INTEGER NOT NULL DEFAULT 0,
    matches_lost       INTEGER NOT NULL DEFAULT 0,
    points_for         INTEGER NOT NULL DEFAULT 0,
    points_against     INTEGER NOT NULL DEFAULT 0,
    current_round      INTEGER NOT NULL DEFAULT 0,

    created_at         TIMESTAMP NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_teams_tournament
        FOREIGN KEY (tournament_id) REFERENCES tournaments (id) ON DELETE CASCADE,
    CONSTRAINT uq_teams_tournament_name UNIQUE (tournament_id, name)
);

-- =====================================================================================
--  TABLA: matches  (llaves del cuadro de eliminacion directa)
-- =====================================================================================
CREATE TABLE matches (
    id                BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tournament_id     BIGINT      NOT NULL,
    round_number      INTEGER     NOT NULL,
    position_in_round INTEGER     NOT NULL,
    home_team_id      BIGINT,
    away_team_id      BIGINT,
    home_score        INTEGER,
    away_score        INTEGER,
    winner_team_id    BIGINT,
    status            VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    scheduled_at      TIMESTAMP,                       -- fecha/hora programada (opcional)
    created_at        TIMESTAMP   NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_matches_tournament
        FOREIGN KEY (tournament_id) REFERENCES tournaments (id) ON DELETE CASCADE,
    CONSTRAINT fk_matches_home_team   FOREIGN KEY (home_team_id)   REFERENCES teams (id) ON DELETE SET NULL,
    CONSTRAINT fk_matches_away_team   FOREIGN KEY (away_team_id)   REFERENCES teams (id) ON DELETE SET NULL,
    CONSTRAINT fk_matches_winner_team FOREIGN KEY (winner_team_id) REFERENCES teams (id) ON DELETE SET NULL,
    CONSTRAINT uq_matches_bracket_slot UNIQUE (tournament_id, round_number, position_in_round),
    CONSTRAINT chk_matches_status CHECK (status IN ('PENDING', 'READY', 'PLAYED')),
    CONSTRAINT chk_matches_winner CHECK (
        winner_team_id IS NULL OR winner_team_id = home_team_id OR winner_team_id = away_team_id
    )
);

-- FK diferida: campeon del torneo (se agrega tras crear teams).
ALTER TABLE tournaments
    ADD CONSTRAINT fk_tournaments_champion_team
        FOREIGN KEY (champion_team_id) REFERENCES teams (id) ON DELETE SET NULL;

-- =====================================================================================
--  TABLA: audit_log  (Criterio 2: quien, que, cuando, valores anteriores/nuevos)
-- =====================================================================================
CREATE TABLE audit_log (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_name VARCHAR(40)  NOT NULL,          -- courts, reservations, tournaments, teams, matches
    entity_id   BIGINT       NOT NULL,
    action      VARCHAR(10)  NOT NULL,
    user_sub    VARCHAR(80)  NOT NULL,          -- sub del token de Cognito
    user_name   VARCHAR(60)  NOT NULL,          -- claim username del token
    old_values  VARCHAR(2000),                  -- enmascarado: nunca correos ni telefonos completos
    new_values  VARCHAR(2000),
    created_at  TIMESTAMP    NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_audit_action CHECK (action IN ('INSERT', 'UPDATE', 'DELETE'))
);

-- Indices de apoyo.
CREATE INDEX idx_reservations_court ON reservations (court_id);
CREATE INDEX idx_reservations_owner ON reservations (owner_user);
CREATE INDEX idx_teams_tournament   ON teams (tournament_id);
CREATE INDEX idx_matches_tournament ON matches (tournament_id, round_number, position_in_round);
CREATE INDEX idx_audit_entity       ON audit_log (entity_name, entity_id);
